name: Build and Checkstyle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4

      - name: Install Maven
        run: |
          sudo apt-get install -y maven

      - name: Build with Maven
        run: |
          mvn clean package

      - name: Run Checkstyle
        run: |
          mvn checkstyle:check

      - name: Run Docker Compose
        run: |
          docker-compose -f courses/docker/docker-compose.yml up

      - name: Run Postman Tests
        uses: postman/pm@v2.4.3
        with:
          collection: 'courses/postman/CoursesTest.postman_collection.json'
          tests: 'courses/postman/CoursesTest.postman_ tests.json'

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: target/*.jar