name: Build and Checkstyle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install Maven
        run: |
          sudo apt-get install -y maven

      - name: Build with Maven
        run: |
          mvn clean package

      - name: Run Checkstyle
        run: |
          mvn checkstyle:check

      - name: Run Docker Compose Build
        run: |
          docker-compose -f docker-compose.yml build

      - name: Run Docker Compose Up
        run: |
          docker-compose -f docker-compose.yml up -d

      - name: Run Postman Tests
        id: run-newman
        uses: anthonyvscode/newman-action@v1
        with:
          collection: postman-tests.json
          reporters: cli

      - name: Output summary to console
        run: echo ${{ steps.run-newman.outputs.summary }}

      - name: Run Docker Compose Down
        run: |
          docker-compose -f docker-compose.yml down

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: target/*.jar