name: Build and Checkstyle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        run: |
          sudo apt-get update
          sudo apt-get install -y default-jdk
          export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64

      - name: Install Maven
        run: |
          sudo apt-get install -y maven

      - name: Build with Maven
        run: |
          mvn clean package

      - name: Run Checkstyle
        run: |
          mvn checkstyle:check

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: target/*.jar