name: Build and Checkstyle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4

      - name: Install Maven
        run: |
          sudo apt-get install -y maven

      - name: Install dependencies
        run: npm install

      - name: Install newman
        run: npm install -g newman

      - name: Build with Maven
        run: |
          mvn clean package

      - name: Run Checkstyle
        run: |
          mvn checkstyle:check

      - name: Run Docker Compose Up
        run: |
          docker-compose -f courses/docker/docker-compose.yml up

      - name: Run Postman Tests
        run: |
          npm run start:dev &
          sleep 60
          newman run 'courses/postman/CoursesTest.postman_collection.json'

      - name: Run Docker Compose Down
        run: |
          docker-compose -f courses/docker/docker-compose.yml down

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: target/*.jar